# 1. 아래 배열에서 M 이 몇번 나오는지 출력하는 코드를 작성하시오
data_list = ['Braund, Mr. Owen Harris',
             'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
             'Heikkinen, Miss. Laina',
             'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
             'Allen, Mr. William Henry',
             'Moran, Mr. James',
             'McCarthy, Mr. Timothy J',
             'Palsson, Master. Gosta Leonard',
             'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
             'Nasser, Mrs. Nicholas (Adele Achem)',
             'Sandstrom, Miss. Marguerite Rut',
             'Bonnell, Miss. Elizabeth',
             'Saundercock, Mr. William Henry',
             'Andersson, Mr. Anders Johan',
             'Vestrom, Miss. Hulda Amanda Adolfina',
             'Hewlett, Mrs. (Mary D Kingcome) ',
             'Rice, Master. Eugene',
             'Williams, Mr. Charles Eugene',
             'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
             'Masselmani, Mrs. Fatima',
             'Fynney, Mr. Joseph J',
             'Beesley, Mr. Lawrence',
             'McGowan, Miss. Anna "Annie"',
             'Sloper, Mr. William Thompson',
             'Palsson, Miss. Torborg Danira',
             'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
             'Emir, Mr. Farred Chehab',
             'Fortune, Mr. Charles Alexander',
             'Dwyer, Miss. Ellen "Nellie"',
             'Todoroff, Mr. Lalio']

# 1. 랜덤한 정수형 데이터를 가지는 배열 a에 대해 각 요소의 값이 0보다 클 때 출력하는 코드를 작성하시오
a = [1, 2, 3, 4, -2, 5, 6]
